services:
  dev-lambda-python:
    container_name: dev-lambda-python
    build: ./dev-lambda-python
    environment:
      AWS_ACCESS_KEY_ID: dummy
      AWS_SECRET_ACCESS_KEY: dummy
      AWS_DEFAULT_REGION: ap-northeast-1
      AWS_ENDPOINT_URL: http://localstack:4566
    volumes:
      - ./../:/workspace
    tty: true
  mysql:
    container_name: mysql-app
    build: ./mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      TZ: Asia/Tokyo
    volumes:
      - ./mysql/initdb.d:/docker-entrypoint-initdb.d
      - ./mysql/conf.d/config.cnf:/etc/mysql/conf.d/config.cnf
      - ./mysql/app-db-data:/var/lib/mysql
    ports:
      - 3306:3306
    tty: true
  localstack:
    container_name: localstack
    build: ./localstack
    ports:
      - 4566:4566
    environment:
      AWS_ACCESS_KEY_ID: dummy
      AWS_SECRET_ACCESS_KEY: dummy
      AWS_DEFAULT_REGION: ap-northeast-1
      AWS_ENDPOINT_URL: http://localhost:4566
      DEFAULT_REGION: ap-northeast-1
      DEBUG: 1
    volumes:
      - ./localstack/ready.d:/etc/localstack/init/ready.d
      - ./localstack/var/lib/localstack:/var/lib/localstack
      - ./localstack/var/run/docker.sock:/var/run/docker.sock
    tty: true
